export const AllProducts = [
  {
    id: 1,
    name: "Menswear FTS100 Fitness Cardio T-Shirt",
    description:
      "Manufacturer & Exporters of Mens Half Sleeve T Shirt in Nashik India. Kiran Enterprises offering fine quality Mens Half Sleeve T Shirt at Affordable ...",
    image: [
      "Image/01.png",
      "Image/ProductViewer/Ellipse 4.png",
      "Image/ProductViewer/Ellipse 5.png",
      "Image/ProductViewer/Ellipse 6.png",
    ],
    price: 499.0,
    discount: 10,
    rating: 4.8,
    size: ["S", "M", "L", "XL"],
    color: ["3d0008", "3f3f3f", "000101"],
    NeckType: "Round Neck",
    Material: "Cotton",
    Pattern: "Plain",
    SleeveType: "Half",
    Occasion: "Daily",
    Feature: "Easily Washable",
    availableShop: [1, 2],
  },
  {
    id: 2,
    name: "Menswear FTS100 Fitness Cardio T-Shirt",
    description:
      "Manufacturer & Exporters of Mens Half Sleeve T Shirt in Nashik India. Kiran Enterprises offering fine quality Mens Half Sleeve T Shirt at Affordable ...",
    image: [
      "Image/feature.png",
      "Image/ProductViewer/Ellipse 4.png",
      "Image/ProductViewer/Ellipse 5.png",
      "Image/ProductViewer/Ellipse 6.png",
    ],
    price: 499.0,
    discount: 20,
    rating: 4.8,
    size: ["S", "L", "XL"],
    color: ["3d0008", "3f3f3f", "000101"],
    NeckType: "Round Neck",
    Material: "Cotton",
    Pattern: "Plain",
    SleeveType: "Half",
    Occasion: "Daily",
    Feature: "Easily Washable",
    availableShop: [1, 2],
  },
  {
    id: 3,
    name: "Menswear FTS100 Fitness Cardio T-Shirt",
    description:
      "Manufacturer & Exporters of Mens Half Sleeve T Shirt in Nashik India. Kiran Enterprises offering fine quality Mens Half Sleeve T Shirt at Affordable ...",
    image: [
      "Image/Trending.png",
      "Image/ProductViewer/Ellipse 4.png",
      "Image/ProductViewer/Ellipse 5.png",
      "Image/ProductViewer/Ellipse 6.png",
    ],
    price: 600.0,
    discount: 50,
    rating: 4.0,
    size: [],
    color: ["3d0008", "3f3f3f", "000101"],
    NeckType: "Round Neck",
    Material: "Cotton",
    Pattern: "Plain",
    SleeveType: "Half",
    Occasion: "Daily",
    Feature: "Easily Washable",
    availableShop: [1, 2],
  },
  {
    id: 4,
    name: "Menswear FTS100 Fitness Cardio T-Shirt",
    description:
      "Manufacturer & Exporters of Mens Half Sleeve T Shirt in Nashik India. Kiran Enterprises offering fine quality Mens Half Sleeve T Shirt at Affordable ...",
    image: [
      "Image/ProductViewer/Ellipse 4.png",
      "Image/ProductViewer/Ellipse 5.png",
      "Image/ProductViewer/Ellipse 6.png",
    ],
    price: 499.0,
    discount: 10,
    rating: 4.8,
    size: [],
    color: [],
    NeckType: "Round Neck",
    Material: "Cotton",
    Pattern: "Plain",
    SleeveType: "Half",
    Occasion: "Daily",
    Feature: "Easily Washable",
    availableShop: [1, 2],
  },
  {
    id: 5,
    name: "Menswear FTS100 Fitness Cardio T-Shirt",
    description:
      "Manufacturer & Exporters of Mens Half Sleeve T Shirt in Nashik India. Kiran Enterprises offering fine quality Mens Half Sleeve T Shirt at Affordable ...",
    image: ["Image/trending-bottom-wear.png"],
    price: 499.0,
    discount: 10,
    rating: 4.8,
    size: [],
    color: [],
    NeckType: "Round Neck",
    Material: "Cotton",
    Pattern: "Plain",
    SleeveType: "Half",
    Occasion: "Daily",
    Feature: "Easily Washable",
    availableShop: [1, 2],
  },
  {
    id: 6,
    name: "Menswear FTS100 Fitness Cardio T-Shirt",
    description:
      "Manufacturer & Exporters of Mens Half Sleeve T Shirt in Nashik India. Kiran Enterprises offering fine quality Mens Half Sleeve T Shirt at Affordable ...",
    image: ["Image/available-shop.png"],
    price: 499.0,
    discount: 10,
    rating: 4.8,
    size: [],
    color: [],
    NeckType: "Round Neck",
    Material: "Cotton",
    Pattern: "Plain",
    SleeveType: "Half",
    Occasion: "Daily",
    Feature: "Easily Washable",
    availableShop: [1, 2],
  },
  {
    id: 7,
    name: "Menswear FTS100 Fitness Cardio T-Shirt",
    description:
      "Manufacturer & Exporters of Mens Half Sleeve T Shirt in Nashik India. Kiran Enterprises offering fine quality Mens Half Sleeve T Shirt at Affordable ...",
    image: ["Image/popular brands.png"],
    price: 499.0,
    discount: 10,
    rating: 4.8,
    size: [],
    color: [],
    NeckType: "Round Neck",
    Material: "Cotton",
    Pattern: "Plain",
    SleeveType: "Half",
    Occasion: "Daily",
    Feature: "Easily Washable",
    availableShop: [1, 2],
  },
];

export const DealsOfTheDay = [1, 1, 1, 1, 1, 1, 1];

export const FeaturedProduct = [2, 2, 2, 2, 2];
export const TrendingInFootware = [3, 3, 3, 3, 3];
export const TrendingInTopwear = [4, 4, 4, 4, 4];
export const TrendingInBottomwear = [5, 5, 5, 5, 5];
